server:
  port: 8090
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: /templates/
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: demo
#    password: demo
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml #也可以使用spring.mvc.static-path-pattern: /resources/**
logging:
  path: /log/
  file: webdemoone.log
  level:
    com.example.demo: debug
com:
  cn:
    username: hello
    password: 123